name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write # 顯式宣告需要寫入權限
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web --release --base-href /Nim/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # 升級到 v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
